# Generated by Django 5.2.7 on 2026-01-21 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Job title/position name', max_length=200)),
                ('required_skills', models.TextField(help_text='Required skills separated by commas (e.g., Python, Django, REST API)')),
                ('description', models.TextField(help_text='Detailed job description')),
                ('company', models.CharField(default='Not Specified', max_length=200)),
                ('location', models.CharField(blank=True, default='Remote', max_length=200)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this job currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Job',
                'verbose_name_plural': 'Jobs',
                'ordering': ['-created_at'],
            },
        ),
    ]
